name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t nvm-dev .
      - name: Run tests in container
        run: docker run --rm nvm-dev bash -c "npm test || true"
